import { demoUsers, authenticate, validatePatient, validateAppointment, formatDate, escapeHtml } from './core.js';

const seedPatients = [
  { id: 1, name: 'Marina Costa', cpf: '472.891.360-04', phone: '(41) 99821-4430', email: 'marina.costa@email.com', birth: '1991-03-18', status: 'Ativo', initials: 'MC' },
  { id: 2, name: 'Carlos Oliveira', cpf: '138.502.790-21', phone: '(41) 99120-7781', email: 'carlos.oliveira@email.com', birth: '1978-11-02', status: 'Ativo', initials: 'CO' },
  { id: 3, name: 'Ana Beatriz Souza', cpf: '620.473.150-90', phone: '(41) 99773-6210', email: 'ana.souza@email.com', birth: '1986-07-26', status: 'Ativo', initials: 'AS' },
  { id: 4, name: 'João Pedro Lima', cpf: '905.316.280-15', phone: '(41) 99902-1834', email: 'joao.lima@email.com', birth: '2000-01-09', status: 'Inativo', initials: 'JL' }
];

const seedAppointments = [
  { id: 1, patient: 'Marina Costa', professional: 'Dr. Rafael Lima', specialty: 'Cardiologia', date: '2026-08-25', time: '09:30', type: 'Presencial', status: 'Confirmada' },
  { id: 2, patient: 'Carlos Oliveira', professional: 'Dra. Luiza Gomes', specialty: 'Clínica Geral', date: '2026-08-25', time: '11:00', type: 'Teleconsulta', status: 'Confirmada' },
  { id: 3, patient: 'Ana Beatriz Souza', professional: 'Dr. Rafael Lima', specialty: 'Cardiologia', date: '2026-08-27', time: '14:30', type: 'Retorno', status: 'Pendente' }
];

const state = {
  user: JSON.parse(sessionStorage.getItem('sghss_user') || 'null'),
  page: 'dashboard',
  patients: JSON.parse(localStorage.getItem('sghss_patients') || 'null') || seedPatients,
  appointments: JSON.parse(localStorage.getItem('sghss_appointments') || 'null') || seedAppointments,
  query: '', modal: null
};

const pagesByRole = {
  Paciente: [['dashboard','⌂','Visão geral'],['schedule','□','Agendamentos'],['record','◎','Meu prontuário'],['telemedicine','◉','Telemedicina']],
  Profissional: [['dashboard','⌂','Visão geral'],['schedule','□','Minha agenda'],['patients','♙','Pacientes'],['record','◎','Prontuários'],['telemedicine','◉','Telemedicina']],
  Administrador: [['dashboard','⌂','Visão geral'],['patients','♙','Pacientes'],['schedule','□','Agendamentos'],['professionals','♧','Profissionais'],['reports','▥','Relatórios']]
};

const app = document.querySelector('#app');
const persist = () => { localStorage.setItem('sghss_patients', JSON.stringify(state.patients)); localStorage.setItem('sghss_appointments', JSON.stringify(state.appointments)); };
const toast = (message, error=false) => { const el=document.createElement('div'); el.className=`toast${error?' error':''}`; el.textContent=message; document.querySelector('#toast-region').append(el); setTimeout(()=>el.remove(),3500); };
const titleFor = page => ({dashboard:'Visão geral',patients:'Pacientes',schedule:'Agendamentos',record:'Prontuário eletrônico',telemedicine:'Telemedicina',professionals:'Profissionais',reports:'Relatórios'}[page]);

function render() {
  if (!state.user) return renderLogin();
  const nav = pagesByRole[state.user.role];
  app.innerHTML = `<div class="app-shell">
    <aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark">+</span> VidaPlus</div>
      <div class="nav-group">Navegação</div>${nav.map(([id,icon,label])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join('')}
      <div class="nav-group">Suporte</div><button class="nav-item" data-help><span class="nav-icon">?</span>Central de ajuda</button>
      <div class="profile-mini"><span class="avatar">${state.user.initials}</span><div><strong>${state.user.name}</strong><small>${state.user.role}</small></div><button class="logout" title="Sair" aria-label="Sair">↪</button></div>
    </aside>
    <main class="main-area" id="main-content"><header class="topbar"><div style="display:flex;align-items:center;gap:12px"><button class="icon-button mobile-menu" aria-label="Abrir menu">☰</button><div class="topbar-title"><h1>${titleFor(state.page)}</h1><p>Unidade VidaPlus Centro · Curitiba</p></div></div><div class="top-actions"><button class="icon-button" aria-label="Notificações">♢<span class="notification-dot"></span></button><button class="btn btn-ghost" data-profile>Trocar perfil</button></div></header><section id="page-content">${renderPage()}</section></main>
    ${renderModal()}
  </div>`;
  bindCommon(); bindPage();
}

function renderLogin() {
  app.innerHTML = `<main class="login-shell"><section class="login-visual"><div class="brand"><span class="brand-mark">+</span> VidaPlus</div><div class="visual-copy"><span class="eyebrow" style="color:#baf3ec">Cuidado integrado</span><h1>Saúde conectada, cuidado humano.</h1><p>Uma plataforma segura para aproximar pacientes, profissionais e a gestão hospitalar.</p></div><div class="trust-row"><span>Dados protegidos</span><span>Atendimento integrado</span><span>Conforme a LGPD</span></div></section><section class="login-panel"><div class="login-card"><span class="eyebrow">Portal SGHSS</span><h2>Boas-vindas</h2><p class="lead">Acesse sua conta para continuar.</p><form id="login-form" novalidate><div class="field"><label for="email">E-mail</label><input id="email" name="email" type="email" autocomplete="username" placeholder="seuemail@exemplo.com" required><small class="error-text" id="login-error"></small></div><div class="field"><label for="password">Senha</label><div class="password-wrap"><input id="password" name="password" type="password" autocomplete="current-password" placeholder="Digite sua senha" required><button class="text-button" type="button" id="toggle-password">Mostrar</button></div></div><button class="btn btn-primary btn-block" type="submit">Entrar no sistema</button></form><div class="demo-box"><strong>Acessos de demonstração</strong><div class="demo-buttons"><button data-demo="paciente">Paciente</button><button data-demo="profissional">Profissional</button><button data-demo="administrador">Administrador</button></div><small>Senha para todos os perfis: 123456</small></div></div></section></main>`;
  document.querySelector('#toggle-password').onclick=e=>{const input=document.querySelector('#password');input.type=input.type==='password'?'text':'password';e.target.textContent=input.type==='password'?'Mostrar':'Ocultar'};
  document.querySelectorAll('[data-demo]').forEach(btn=>btn.onclick=()=>{ const u=demoUsers[btn.dataset.demo]; document.querySelector('#email').value=u.email; document.querySelector('#password').value=u.password; });
  document.querySelector('#login-form').onsubmit=e=>{ e.preventDefault(); const data=new FormData(e.target); const user=authenticate(data.get('email'),data.get('password')); if(!user){document.querySelector('#login-error').textContent='E-mail ou senha incorretos. Use um dos acessos de demonstração.';return;} state.user=user; state.page='dashboard'; sessionStorage.setItem('sghss_user',JSON.stringify(user)); render(); toast(`Olá, ${user.name.split(' ')[0]}! Acesso realizado com sucesso.`); };
}

function renderPage(){ return ({dashboard:dashboardPage,patients:patientsPage,schedule:schedulePage,record:recordPage,telemedicine:telemedicinePage,professionals:professionalsPage,reports:reportsPage}[state.page]||dashboardPage)(); }

function dashboardPage(){
  const role=state.user.role; const patient=role==='Paciente';
  return `<div class="hero"><div><h2>${patient?'Seu cuidado, em um só lugar.':'Olá, '+state.user.name.split(' ')[0]+'. Bom trabalho!'}</h2><p>${patient?'Acompanhe consultas, exames e informações do seu tratamento.':'Confira os indicadores e compromissos da unidade hoje.'}</p></div><button class="btn" data-open="appointment">${patient?'＋ Agendar consulta':'＋ Novo atendimento'}</button></div>
  <div class="stats"><article class="card stat-card"><div class="stat-top"><span>${patient?'Próxima consulta':'Consultas hoje'}</span><span class="stat-icon">□</span></div><div class="stat-value">${patient?'25 ago':'18'}</div><div class="stat-note positive">${patient?'Cardiologia · 09:30':'+12% em relação à média'}</div></article><article class="card stat-card"><div class="stat-top"><span>${patient?'Exames disponíveis':'Pacientes ativos'}</span><span class="stat-icon">♙</span></div><div class="stat-value">${patient?'3':state.patients.filter(p=>p.status==='Ativo').length.toLocaleString('pt-BR')}</div><div class="stat-note">${patient?'1 resultado novo':'Base da unidade Centro'}</div></article><article class="card stat-card"><div class="stat-top"><span>${patient?'Prescrições':'Ocupação de leitos'}</span><span class="stat-icon">✚</span></div><div class="stat-value">${patient?'2':'78%'}</div><div class="stat-note">${patient?'1 receita vigente':'39 de 50 leitos'}</div></article><article class="card stat-card"><div class="stat-top"><span>${patient?'Notificações':'Teleconsultas'}</span><span class="stat-icon">◉</span></div><div class="stat-value">${patient?'1':'6'}</div><div class="stat-note">${patient?'Confirme sua consulta':'2 aguardando início'}</div></article></div>
  <div class="content-grid"><article class="card panel"><div class="panel-header"><h3 class="panel-title">Próximos atendimentos</h3><button class="text-button" data-page="schedule">Ver agenda completa</button></div><div class="appointment-list">${state.appointments.slice(0,3).map(appointmentCard).join('')}</div></article><article class="card panel"><div class="panel-header"><h3 class="panel-title">Atividade recente</h3></div><div class="activity-list"><div class="activity"><span class="activity-dot"></span><div><p>Resultado de hemograma disponível</p><small>Hoje, às 08:42</small></div></div><div class="activity"><span class="activity-dot"></span><div><p>Consulta de cardiologia confirmada</p><small>Ontem, às 16:10</small></div></div><div class="activity"><span class="activity-dot"></span><div><p>Prontuário atualizado com segurança</p><small>22 de agosto</small></div></div></div></article></div>`;
}
function appointmentCard(a){const d=new Date(`${a.date}T12:00:00`);return `<div class="appointment"><div class="date-tile"><strong>${String(d.getDate()).padStart(2,'0')}</strong><small>${d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></div><div><h4>${escapeHtml(a.specialty)}</h4><p>${escapeHtml(a.professional)} · ${a.time} · ${escapeHtml(a.type)}</p></div><span class="badge ${a.status==='Pendente'?'warning':''}">${a.status}</span></div>`}

function patientsPage(){const q=state.query.toLowerCase();const list=state.patients.filter(p=>`${p.name} ${p.cpf} ${p.email}`.toLowerCase().includes(q));return `<div class="page-header"><div><h2>Gestão de pacientes</h2><p>Cadastros e informações clínicas centralizadas.</p></div><button class="btn btn-primary" data-open="patient">＋ Novo paciente</button></div><div class="toolbar"><label class="search"><span>⌕</span><input id="patient-search" value="${escapeHtml(state.query)}" placeholder="Buscar por nome, CPF ou e-mail" aria-label="Buscar pacientes"></label><button class="btn btn-ghost">☷ Filtros</button></div><article class="card table-wrap"><table class="data-table"><thead><tr><th>Paciente</th><th>CPF</th><th>Contato</th><th>Status</th><th>Ações</th></tr></thead><tbody>${list.map(p=>`<tr><td><div class="patient-name"><span class="avatar">${p.initials}</span><div><strong>${escapeHtml(p.name)}</strong><br><small>${formatDate(p.birth)}</small></div></div></td><td>${p.cpf}</td><td>${p.phone}<br><small>${escapeHtml(p.email)}</small></td><td><span class="badge ${p.status==='Inativo'?'warning':''}">${p.status}</span></td><td><div class="actions"><button title="Ver prontuário" data-record="${p.id}">◎</button><button title="Editar cadastro" data-edit="${p.id}">✎</button></div></td></tr>`).join('')}</tbody></table>${!list.length?'<div class="empty">Nenhum paciente encontrado.</div>':''}</article>`}

function schedulePage(){return `<div class="page-header"><div><h2>Agenda de atendimentos</h2><p>Semana de 24 a 28 de agosto de 2026.</p></div><button class="btn btn-primary" data-open="appointment">＋ Novo agendamento</button></div><div class="schedule-layout"><article class="card calendar"><div class="calendar-head"><button class="btn btn-ghost">‹</button><strong>Agosto de 2026</strong><button class="btn btn-ghost">›</button></div><div class="week-grid">${[['SEG','24'],['TER','25'],['QUA','26'],['QUI','27'],['SEX','28']].map(([day,n],i)=>`<div class="day-column"><div class="day-label">${day}<strong>${n}</strong></div>${state.appointments.filter(a=>new Date(`${a.date}T12:00:00`).getDate()==Number(n)).map((a,j)=>`<div class="event ${j%2?'blue':''}"><strong>${a.time} · ${escapeHtml(a.patient)}</strong>${escapeHtml(a.specialty)}<br>${escapeHtml(a.type)}</div>`).join('')}</div>`).join('')}</div></article><aside class="card panel"><div class="panel-header"><h3 class="panel-title">Resumo do dia</h3></div><div class="activity-list"><div class="stat-card" style="background:var(--primary-soft);border-radius:12px"><div class="stat-top">Atendimentos</div><div class="stat-value">18</div><div class="stat-note">12 presenciais · 6 remotos</div></div><div class="activity"><span class="activity-dot"></span><div><p>09:30 · Marina Costa</p><small>Cardiologia · Confirmada</small></div></div><div class="activity"><span class="activity-dot"></span><div><p>11:00 · Carlos Oliveira</p><small>Teleconsulta · Confirmada</small></div></div></div></aside></div>`}

function recordPage(){return `<div class="page-header"><div><h2>Prontuário eletrônico</h2><p>Histórico clínico protegido e integrado.</p></div>${state.user.role!=='Paciente'?'<button class="btn btn-primary" data-open="record">＋ Nova evolução</button>':''}</div><article class="card record-hero"><span class="avatar">MC</span><div><h3 style="margin:0">Marina Costa</h3><div class="record-meta"><span>CPF 472.891.360-04</span><span>35 anos</span><span>Tipo sanguíneo O+</span><span class="badge">Sem alergias conhecidas</span></div></div></article><div class="content-grid" style="margin-top:18px"><article class="card panel"><div class="panel-header"><h3 class="panel-title">Histórico de atendimentos</h3></div><div class="timeline"><div class="timeline-item"><h4>Consulta cardiológica</h4><p>18/08/2026 · Dr. Rafael Lima</p><p>Paciente estável, pressão arterial 120/80 mmHg. Mantida conduta terapêutica e solicitado novo eletrocardiograma.</p></div><div class="timeline-item"><h4>Exames laboratoriais</h4><p>02/06/2026 · Laboratório VidaPlus</p><p>Hemograma completo e perfil lipídico. Resultados dentro dos valores de referência.</p></div><div class="timeline-item"><h4>Consulta clínica geral</h4><p>14/03/2026 · Dra. Luiza Gomes</p><p>Acompanhamento de rotina. Sem intercorrências.</p></div></div></article><aside class="card panel"><div class="panel-header"><h3 class="panel-title">Informações clínicas</h3></div><p><small>CONDIÇÕES ATIVAS</small><br><strong>Hipertensão arterial leve</strong></p><hr style="border:0;border-top:1px solid var(--line)"><p><small>MEDICAÇÃO EM USO</small><br><strong>Losartana 50 mg</strong><br><span style="color:var(--muted)">1 comprimido ao dia</span></p><hr style="border:0;border-top:1px solid var(--line)"><p><small>ÚLTIMA ATUALIZAÇÃO</small><br><strong>18/08/2026 às 10:32</strong></p></aside></div>`}

function telemedicinePage(){return `<div class="page-header"><div><h2>Atendimento por telemedicina</h2><p>Conexão segura e registro integrado ao prontuário.</p></div></div><article class="card tele-card"><div><span class="eyebrow" style="color:#9fe6dc">Próxima teleconsulta</span><h2>Clínica Geral · 25 de agosto, 11:00</h2><p>Entre na sala até 10 minutos antes para testar áudio e vídeo.</p></div><button class="btn btn-primary" id="join-call">◉ Entrar na sala</button></article><article class="card panel" style="margin-top:18px"><div class="panel-header"><h3 class="panel-title">Antes da consulta</h3></div><div class="stats" style="margin:0"><div class="stat-card"><span class="stat-icon">✓</span><h4>Ambiente reservado</h4><p class="stat-note">Procure um local silencioso e iluminado.</p></div><div class="stat-card"><span class="stat-icon">♬</span><h4>Áudio e câmera</h4><p class="stat-note">Autorize o navegador quando solicitado.</p></div><div class="stat-card"><span class="stat-icon">▣</span><h4>Documentos</h4><p class="stat-note">Tenha exames e documento de identidade.</p></div><div class="stat-card"><span class="stat-icon">⌁</span><h4>Conexão segura</h4><p class="stat-note">A sessão é protegida e confidencial.</p></div></div></article>`}

function professionalsPage(){const docs=[['Dr. Rafael Lima','Cardiologia','CRM-PR 45821','Disponível'],['Dra. Luiza Gomes','Clínica Geral','CRM-PR 38210','Em atendimento'],['Enf. Paulo Nunes','Enfermagem','COREN-PR 184392','Disponível'],['Dra. Camila Rocha','Pediatria','CRM-PR 52671','Ausente']];return `<div class="page-header"><div><h2>Profissionais de saúde</h2><p>Equipe, especialidades e disponibilidade.</p></div><button class="btn btn-primary">＋ Novo profissional</button></div><article class="card table-wrap"><table class="data-table"><thead><tr><th>Profissional</th><th>Especialidade</th><th>Registro</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${docs.map((d,i)=>`<tr><td><div class="patient-name"><span class="avatar">${d[0].split(' ').slice(-2).map(x=>x[0]).join('')}</span><strong>${d[0]}</strong></div></td><td>${d[1]}</td><td>${d[2]}</td><td><span class="badge ${i>0?'blue':''}">${d[3]}</span></td><td><div class="actions"><button>✎</button><button>□</button></div></td></tr>`).join('')}</tbody></table></article>`}

function reportsPage(){return `<div class="page-header"><div><h2>Indicadores gerenciais</h2><p>Visão consolidada das operações da rede.</p></div><button class="btn btn-ghost">⇩ Exportar relatório</button></div><div class="stats"><article class="card stat-card"><div class="stat-top"><span>Atendimentos/mês</span><span class="stat-icon">↗</span></div><div class="stat-value">1.284</div><div class="stat-note positive">+8,2% no período</div></article><article class="card stat-card"><div class="stat-top"><span>Taxa de ocupação</span><span class="stat-icon">▤</span></div><div class="stat-value">78%</div><div class="stat-note">Meta: até 85%</div></article><article class="card stat-card"><div class="stat-top"><span>Tempo médio de espera</span><span class="stat-icon">◷</span></div><div class="stat-value">18 min</div><div class="stat-note positive">-4 min no período</div></article><article class="card stat-card"><div class="stat-top"><span>Satisfação</span><span class="stat-icon">☆</span></div><div class="stat-value">92%</div><div class="stat-note">436 avaliações</div></article></div><div class="content-grid"><article class="card panel"><h3 class="panel-title">Atendimentos por unidade</h3><div style="height:270px;display:flex;align-items:flex-end;gap:24px;padding:30px 20px 0">${[['Centro',88],['Batel',64],['Norte',73],['Home care',48],['Telemed.',58]].map(([n,v])=>`<div style="flex:1;text-align:center;font-size:12px;color:var(--muted)"><div style="height:${v*2}px;background:linear-gradient(var(--primary),#62bcae);border-radius:8px 8px 2px 2px;margin-bottom:8px" title="${v} atendimentos"></div>${n}</div>`).join('')}</div></article><article class="card panel"><h3 class="panel-title">Conformidade e disponibilidade</h3><div class="stat-value positive">99,7%</div><p class="stat-note">Disponibilidade nos últimos 30 dias</p><hr style="border:0;border-top:1px solid var(--line)"><p>✓ Backups verificados</p><p>✓ Auditoria sem alertas críticos</p><p>✓ Consentimentos LGPD atualizados</p></article></div>`}

function renderModal(){if(!state.modal)return '';if(state.modal==='video')return `<div class="modal-backdrop"><div class="modal" style="width:min(880px,100%)"><div class="modal-head"><h3>Teleconsulta · Dra. Luiza Gomes</h3><button class="modal-close">×</button></div><div class="modal-body"><div class="video-placeholder"><div class="video-controls"><button title="Microfone">♬</button><button title="Câmera">▣</button><button class="hangup" title="Encerrar">×</button></div></div><p style="text-align:center;color:var(--muted)">Sala simulada para demonstração do fluxo de telemedicina.</p></div></div></div>`;if(state.modal==='profile')return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>Visualizar como</h3><button class="modal-close">×</button></div><div class="modal-body"><p class="lead">Alterne entre os perfis para demonstrar o controle de acesso.</p><div class="demo-buttons">${Object.entries(demoUsers).map(([id,u])=>`<button data-switch="${id}" style="padding:16px;flex:1">${u.role}</button>`).join('')}</div></div></div></div>`;const isPatient=state.modal==='patient';const isAppointment=state.modal==='appointment';return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>${isPatient?'Cadastrar paciente':isAppointment?'Novo agendamento':'Registrar evolução clínica'}</h3><button class="modal-close" aria-label="Fechar">×</button></div><form class="modal-body" id="modal-form" novalidate>${isPatient?patientForm():isAppointment?appointmentForm():recordForm()}<div class="modal-actions"><button class="btn btn-ghost modal-close-action" type="button">Cancelar</button><button class="btn btn-primary" type="submit">Salvar</button></div></form></div></div>`}
function patientForm(){return `<div class="form-grid"><div class="field full"><label>Nome completo *</label><input name="name" placeholder="Ex.: Maria da Silva"><small class="error-text" data-error="name"></small></div><div class="field"><label>CPF *</label><input name="cpf" placeholder="000.000.000-00" maxlength="14"><small class="error-text" data-error="cpf"></small></div><div class="field"><label>Data de nascimento *</label><input name="birth" type="date"><small class="error-text" data-error="birth"></small></div><div class="field"><label>Telefone *</label><input name="phone" placeholder="(00) 00000-0000" maxlength="15"><small class="error-text" data-error="phone"></small></div><div class="field"><label>E-mail *</label><input name="email" type="email" placeholder="nome@email.com"><small class="error-text" data-error="email"></small></div><div class="field full"><label><input name="consent" type="checkbox" required style="width:auto"> Consentimento para tratamento de dados pessoais conforme a LGPD.</label></div></div>`}
function appointmentForm(){return `<div class="form-grid"><div class="field full"><label>Paciente *</label><select name="patient"><option>Marina Costa</option>${state.patients.slice(1).map(p=>`<option>${escapeHtml(p.name)}</option>`).join('')}</select></div><div class="field"><label>Especialidade *</label><select name="specialty"><option value="">Selecione</option><option>Cardiologia</option><option>Clínica Geral</option><option>Pediatria</option><option>Ortopedia</option></select><small class="error-text" data-error="specialty"></small></div><div class="field"><label>Profissional *</label><select name="professional"><option value="">Selecione</option><option>Dr. Rafael Lima</option><option>Dra. Luiza Gomes</option><option>Dra. Camila Rocha</option></select><small class="error-text" data-error="professional"></small></div><div class="field"><label>Data *</label><input name="date" type="date" min="2026-08-24"><small class="error-text" data-error="date"></small></div><div class="field"><label>Horário *</label><select name="time"><option value="">Selecione</option><option>08:00</option><option>09:30</option><option>11:00</option><option>14:30</option><option>16:00</option></select><small class="error-text" data-error="time"></small></div><div class="field full"><label>Modalidade *</label><select name="type"><option value="">Selecione</option><option>Presencial</option><option>Teleconsulta</option><option>Retorno</option></select><small class="error-text" data-error="type"></small></div></div>`}
function recordForm(){return `<div class="field"><label>Paciente</label><select><option>Marina Costa</option><option>Carlos Oliveira</option></select></div><div class="field"><label>Evolução clínica *</label><textarea required placeholder="Registre sintomas, avaliação e conduta..."></textarea></div><div class="field"><label>Prescrição ou orientação</label><textarea placeholder="Medicamento, posologia ou orientação..."></textarea></div>`}

function bindCommon(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.modal=null;render()});document.querySelector('.logout').onclick=()=>{sessionStorage.removeItem('sghss_user');state.user=null;render()};document.querySelector('.mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelector('[data-profile]').onclick=()=>{state.modal='profile';render()};document.querySelector('[data-help]').onclick=()=>toast('Central de ajuda: suporte@vidaplus.com');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{state.modal=b.dataset.open;render()});document.querySelectorAll('.modal-close,.modal-close-action').forEach(b=>b.onclick=()=>{state.modal=null;render()});document.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>{state.user=demoUsers[b.dataset.switch];sessionStorage.setItem('sghss_user',JSON.stringify(state.user));state.page='dashboard';state.modal=null;render();toast(`Perfil alterado para ${state.user.role}.`)});}
function bindPage(){const search=document.querySelector('#patient-search');if(search)search.oninput=e=>{state.query=e.target.value;const pos=e.target.selectionStart;render();const n=document.querySelector('#patient-search');n.focus();n.setSelectionRange(pos,pos)};document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>{state.page='record';render()});const join=document.querySelector('#join-call');if(join)join.onclick=()=>{state.modal='video';render()};const hang=document.querySelector('.hangup');if(hang)hang.onclick=()=>{state.modal=null;render();toast('Teleconsulta encerrada e registrada no histórico.')};const form=document.querySelector('#modal-form');if(form)form.onsubmit=handleForm;}
function handleForm(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));let errors={};if(state.modal==='patient')errors=validatePatient(data);if(state.modal==='appointment')errors=validateAppointment(data);e.target.querySelectorAll('[data-error]').forEach(el=>{el.textContent=errors[el.dataset.error]||'';el.previousElementSibling?.classList.toggle('error',!!errors[el.dataset.error])});if(Object.keys(errors).length){toast('Revise os campos destacados.',true);return}if(state.modal==='patient'){data.id=Date.now();data.status='Ativo';data.initials=data.name.split(' ').slice(0,2).map(n=>n[0]).join('').toUpperCase();state.patients.unshift(data)}else if(state.modal==='appointment'){data.id=Date.now();data.status='Confirmada';state.appointments.unshift(data)}persist();state.modal=null;render();toast(state.page==='patients'?'Paciente cadastrado com sucesso.':'Informações salvas com sucesso.');}

render();
